# Generated by Django 4.0.6 on 2022-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familia',
            new_name='familiares',
        ),
    ]
